name: Deploy to GH Pages

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 22
      - name: Set Up GH identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Installing dependencies...
        run: npm ci
      - name: Building...
        run: npm run build
      - name: Deploy 🚀
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh-pages -d dist -u 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>' -r https://$GH_TOKEN@github.com/Poleron402/web-portfolio.git